// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Webapi__Dom__HtmlInputElement = require("rescript-webapi/lib/js/src/Webapi/Dom/Webapi__Dom__HtmlInputElement.js");

function focus(id) {
  return {
          TAG: /* EnqueueCall */2,
          _0: (function (_enqueue) {
              var ecb = function (param) {
                var elem = Belt_Option.flatMap(Caml_option.nullable_to_opt(document.getElementById(id)), Webapi__Dom__HtmlInputElement.ofElement);
                if (elem !== undefined) {
                  Caml_option.valFromOption(elem).focus();
                } else {
                  console.log([
                        "Attempted to focus a non-existant element of: ",
                        id
                      ]);
                }
                
              };
              var cb = function (param) {
                requestAnimationFrame(ecb);
                
              };
              requestAnimationFrame(cb);
              
            })
        };
}

exports.focus = focus;
/* Webapi__Dom__HtmlInputElement Not a pure module */
